-- =========================================================
-- E-COMMERCE SQL DATA ANALYSIS
-- Product Analysis
-- Database: Maven Analytics E-commerce Dataset
-- Tool: MySQL
-- =========================================================


-- 1. Total revenue generated by each product
SELECT
    p.product_name,
    SUM(o.price_usd) AS total_revenue
FROM products p
JOIN orders o
    ON p.product_id = o.primary_product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC;


-- 2. Top 3 products by total revenue
WITH product_revenue AS (
    SELECT
        p.product_name,
        SUM(o.price_usd) AS total_revenue
    FROM products p
    JOIN orders o
        ON p.product_id = o.primary_product_id
    GROUP BY p.product_name
),
ranked_products AS (
    SELECT
        product_name,
        total_revenue,
        DENSE_RANK() OVER (
            ORDER BY total_revenue DESC
        ) AS revenue_rank
    FROM product_revenue
)
SELECT
    product_name,
    total_revenue
FROM ranked_products
WHERE revenue_rank <= 3
ORDER BY total_revenue DESC;


-- 3. Revenue percentage contributed by the top 3 products
WITH product_revenue AS (
    SELECT
        p.product_name,
        SUM(o.price_usd) AS total_revenue
    FROM products p
    JOIN orders o
        ON p.product_id = o.primary_product_id
    GROUP BY p.product_name
),
ranked_products AS (
    SELECT
        product_name,
        total_revenue,
        DENSE_RANK() OVER (
            ORDER BY total_revenue DESC
        ) AS revenue_rank
    FROM product_revenue
)
SELECT
    product_name,
    total_revenue,
    ROUND(
        total_revenue * 100.0 /
        (SELECT SUM(total_revenue) FROM product_revenue),
        2
    ) AS revenue_percentage
FROM ranked_products
WHERE revenue_rank <= 3
ORDER BY total_revenue DESC;


-- 4. Product revenue by year and month
SELECT
    YEAR(o.created_at) AS year,
    MONTH(o.created_at) AS month,
    p.product_name,
    SUM(o.price_usd) AS total_revenue
FROM products p
JOIN orders o
    ON p.product_id = o.primary_product_id
GROUP BY
    YEAR(o.created_at),
    MONTH(o.created_at),
    p.product_name
ORDER BY
    year,
    month,
    total_revenue DESC;
