-- =========================================================
-- E-COMMERCE SQL DATA ANALYSIS
-- Revenue Analysis
-- Database: Maven Analytics E-commerce Dataset
-- Tool: MySQL
-- =========================================================


-- 1. Total revenue
SELECT
    SUM(price_usd) AS total_revenue
FROM orders;


-- 2. Revenue by year
SELECT
    YEAR(created_at) AS year,
    SUM(price_usd) AS total_revenue
FROM orders
GROUP BY YEAR(created_at)
ORDER BY year;


-- 3. Monthly revenue for 2013
SELECT
    MONTH(created_at) AS month,
    SUM(price_usd) AS total_revenue
FROM orders
WHERE YEAR(created_at) = 2013
GROUP BY MONTH(created_at)
ORDER BY month;


-- 4. Month with the highest revenue in 2013
SELECT
    month,
    total_revenue
FROM (
    SELECT
        MONTH(created_at) AS month,
        SUM(price_usd) AS total_revenue,
        DENSE_RANK() OVER (
            ORDER BY SUM(price_usd) DESC
        ) AS revenue_rank
    FROM orders
    WHERE YEAR(created_at) = 2013
    GROUP BY MONTH(created_at)
) AS ranked_months
WHERE revenue_rank = 1;


-- 5. Month-over-month revenue growth for 2013
WITH monthly_revenue AS (
    SELECT
        MONTH(created_at) AS month,
        SUM(price_usd) AS total_revenue
    FROM orders
    WHERE YEAR(created_at) = 2013
    GROUP BY MONTH(created_at)
),
previous_month AS (
    SELECT
        month,
        total_revenue,
        LAG(total_revenue) OVER (
            ORDER BY month
        ) AS previous_month_revenue
    FROM monthly_revenue
)
SELECT
    month,
    total_revenue,
    previous_month_revenue,
    ROUND(
        (total_revenue - previous_month_revenue)
        / previous_month_revenue * 100,
        2
    ) AS growth_percentage
FROM previous_month
ORDER BY month;


-- 6. Top 5 users by total revenue
SELECT
    user_id,
    SUM(price_usd) AS total_revenue
FROM orders
GROUP BY user_id
ORDER BY total_revenue DESC
LIMIT 5;


-- 7. Top 3 users by revenue using DENSE_RANK
WITH customer_revenue AS (
    SELECT
        user_id,
        SUM(price_usd) AS total_revenue,
        DENSE_RANK() OVER (
            ORDER BY SUM(price_usd) DESC
        ) AS revenue_rank
    FROM orders
    GROUP BY user_id
)
SELECT
    user_id,
    total_revenue
FROM customer_revenue
WHERE revenue_rank <= 3
ORDER BY total_revenue DESC;


-- 8. Revenue percentage generated by each user
WITH customer_revenue AS (
    SELECT
        user_id,
        SUM(price_usd) AS total_revenue
    FROM orders
    GROUP BY user_id
)
SELECT
    user_id,
    total_revenue,
    ROUND(
        total_revenue * 100.0 /
        (SELECT SUM(total_revenue)
         FROM customer_revenue),
        2
    ) AS revenue_percentage
FROM customer_revenue
ORDER BY total_revenue DESC;
